LogicBack/Models/About.cs
namespace LogicBack.Models
{
    public class About
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Image { get; set; }
    }
}

LogicBack/Models/AboutList.cs
namespace LogicBack.Models
{
    public class AboutList
    {
        public int Id { get; set; }
        public string Icon { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
    }
}

LogicBack/Models/Action.cs
namespace LogicBack.Models
{
    public class Action
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Button { get; set; }
    }
}

LogicBack/Models/Icon.cs
namespace LogicBack.Models
{
    public class Icon
    {
        public int Id { get; set; }
        public string IconImage { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
    }
}

LogicBack/Models/Service.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations.Schema;

namespace LogicBack.Models
{
    public class Service
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        [NotMapped]
        public IFormFile Photo { get; set; }
    }
}

LogicBack/Models/Setting.cs
using System.Collections.Generic;

namespace LogicBack.Models
{
    public class Setting
    {
        public int Id { get; set; }
        public string HeaderLogo { get; set; }
        public string FooterLogo { get; set; }
        public List<SocialMedia> SocialMedias { get; set; }
    }
}

LogicBack/Models/Slider.cs
namespace LogicBack.Models
{
    public class Slider
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    }
}

LogicBack/Models/SocialMedia.cs
namespace LogicBack.Models
{
    public class SocialMedia
    {
        public int Id { get; set; }
        public string Icon { get; set; }
        public Setting Settings { get; set; }
        public int SettingId { get; set; }
    }
}

LogicBack/ViewModels/HomeVM.cs
using LogicBack.Models;
using System.Collections.Generic;

namespace LogicBack.ViewModels
{
    public class HomeVM
    {
        public Slider Sliders { get; set; }
        public List<Icon> Icons  { get; set; }
        public About Abouts { get; set; }
        public List<AboutList> AboutLists { get; set; }
        public List<Service> Services { get; set; }
        public Action Actions { get; set; }
        public Setting Settings { get; set; }
        public List<SocialMedia> SocialMedias { get; set; }
    }
}

LogicBack/Areas/LogisAdmin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace LogicBack.Areas.LogisArea.Controllers
{
    [Area("LogisAdmin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

LogicBack/Areas/LogisAdmin/Controllers/ServiceController.cs
using LogicBack.DAL;
using LogicBack.Extentions;
using LogicBack.Models;
using LogicBack.Utilities;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace LogicBack.Areas.LogisArea.Controllers
{
    [Area("LogisAdmin")]
    public class ServiceController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public ServiceController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public async Task<IActionResult> Index()
        {
            List<Service> services = await _context.Services.ToListAsync();
            return View(services);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Create(Service service)
        {
            if (!ModelState.IsValid) return View();
            if (service.Photo!=null)
            {
                if (service.Photo.IsOkay(1))
                {
                    ModelState.AddModelError("Photo", "Zehmet olmasa olcusu 1mb dan kicik olan sekil secin");
                    return View();
                }
                service.Image = await service.Photo.FileCreate(_env.WebRootPath, @"assets\img");
                await _context.SaveChangesAsync();
                await _context.Services.AddAsync(service);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("Photo", "Zehmet olmasa sekil fayli secin");
                return View();
            }
        }
       public async Task<IActionResult> Detail(int id)
        {
            Service service = await _context.Services.FirstOrDefaultAsync(s => s.Id == id);
            if (service == null) return NotFound();
            return View(service);
        }
        public async Task<IActionResult> Delete(int id)
        {
            Service service = await _context.Services.FirstOrDefaultAsync(s => s.Id == id);
            {
                if (service == null) return NotFound();
                return View(service);
            }
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteService(int id)
        {
            Service service = await _context.Services.FirstOrDefaultAsync(s => s.Id == id);
            {
                if (service == null) return NotFound();
                _context.Services.Remove(service);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

LogicBack/Controllers/HomeController.cs
using LogicBack.DAL;
using LogicBack.Models;
using LogicBack.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace LogicBack.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDbContext _context;

        public HomeController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            HomeVM model = new HomeVM
            {
                Sliders = await _context.Sliders.FirstOrDefaultAsync(),
                Icons = await _context.Icons.ToListAsync(),
                Abouts = await _context.Abouts.FirstOrDefaultAsync(),
                AboutLists = await _context.AboutLists.ToListAsync(),
                Services = await _context.Services.ToListAsync(),
                Actions = await _context.Actions.FirstOrDefaultAsync(),
                SocialMedias = await _context.SocialMedias.ToListAsync(),
                Settings = await _context.Settings.FirstOrDefaultAsync(),
            };
           return View(model);
        }
    }
}

LogicBack/ViewComponents/FooterViewComponent.cs
using LogicBack.DAL;
using LogicBack.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace LogicBack.ViewComponents
{
    public class FooterViewComponent:ViewComponent
    {
        private readonly AppDbContext _context;

        public FooterViewComponent(AppDbContext context)
        {
            _context = context;
        }
       public async Task<IViewComponentResult> InvokeAsync()
        {
            HomeVM model = new HomeVM
            {
                Settings = await _context.Settings.FirstOrDefaultAsync(),
                SocialMedias = await _context.SocialMedias.ToListAsync()
            };
            return View(model);
        }
    }
}

LogicBack/ViewComponents/HeaderViewComponent.cs
using LogicBack.DAL;
using LogicBack.Models;
using LogicBack.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace LogicBack.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;

        public HeaderViewComponent(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            HomeVM model = new HomeVM
            {
                Settings = await _context.Settings.FirstOrDefaultAsync(),
                SocialMedias = await _context.SocialMedias.ToListAsync()
            };
            return View(model);
        }
    }
}

LogicBack/Areas/LogisAdmin/Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

LogicBack/Areas/LogisAdmin/Views/Service/Create.cshtml
@model Service
<form method="post" enctype="multipart/form-data">
    <div>
        <label class="mt-3">Title</label><br/>
        <input asp-action="Title" class="form-control" /><br/>
        <span asp-validation-for="Title" class="text-danger"></span>
</div>
<div>
    <label class="mt-3">Subtitle</label><br/>
    <input class="form-control" asp-for="Subtitle"/><br/>
    <span class="text-danger" asp-validation-for="Subtitle"></span>
</div>
<div>
    <label class="mt-3">Image</label><br/>
    <input class="form-control" asp-for="Photo" accept="image/*"/><br/>
    <span class="text-danger" asp-validation-for="Photo"></span>
</div>
<div>
    <button type="submit" class="btn btn-primary">Create service</button>
</div>
</form>

LogicBack/Areas/LogisAdmin/Views/Service/Delete.cshtml
@model Service
<div>
    <div>
        <h4>Id:</h4>
        <p>@Model.Id</p>
    </div>
    <div>
        <h4>Title:</h4>
        <p>@Model.Title</p>
    </div>
    <div>
        <h4>Subtitle</h4>
        <p>@Model.Subtitle</p>
    </div>
    <div>
        <h4>Image:</h4>
        <img style="width:150px;" src="~/assets/img/@Model.Image"/>
    </div>
</div>
<form method="post" class="mt-4">
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

LogicBack/Areas/LogisAdmin/Views/Service/Detail.cshtml
@model Service
<div>
    <div>
        <h4>Id:</h4>
        <p>@Model.Id</p>
    </div>
    <div>
        <h4>Title:</h4>
        <p>@Model.Title</p>
    </div>
    <div>
        <h4>Subtitle:</h4>
        <p>@Model.Subtitle</p>
    </div>
    <div>
        <h4>Image</h4>
        <img style="width:150px;" src="~/assets/img/@Model.Image"/>
    </div>
</div>
  

LogicBack/Areas/LogisAdmin/Views/Service/Index.cshtml
@model List<Service>
@{
    ViewData["Title"] = "Index";
}
<div class="table-responsive pt-3">
    <a asp-controller="Service" asp-action="Create" style="color:white; font-size:20px;" class="my-2 btn btn-lg btn-success">Create service</a>
    <table class="table table-dark">
        <thead>
            <tr>
                <th>
                    Image
                </th>
                <th>
                    Title
                </th>
                <th>
                    Subtitle
                </th>
                <th>
                    Settings
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (Service service in Model)
            {
            <tr>
                <td>
                    <img style="width:150px; height:150px" src="~/assets/img/@service.Image" />
                </td>
                <td>
                    @service.Title
                </td>
                <td>
                    @if (service.Subtitle.Length >= 30)
                    {
                        @(service.Subtitle.Substring(0, 30).ToString() + "...")
                    }
                    else
                    {
                        @service.Subtitle
                    }
                </td>

               
                <td>
                    <div class="d-flex">
                        <div class="detail">
                            <a asp-controller="Service" asp-action="Detail" asp-route-id="@service.Id" class="btn btn-outline-primary"><i class="mdi mdi-details"></i></a>
                        </div>
                        <div class="ms-2 delete">
                            <a asp-controller="Service" asp-action="Delete" asp-route-id="@service.Id" class="btn btn-outline-danger"><i class="mdi mdi-delete-forever"></i></a>
                        </div>
                    </div>
                </td>
            </tr>
            }

        </tbody>
    </table>
</div>

LogicBack/Areas/LogisAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>DASHMIN - Bootstrap Admin Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="~/admin/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/admin/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/admin/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/admin/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/admin/css/style.css" rel="stylesheet">
</head>

<body>
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-light navbar-light">
                <a href="index.html" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary"><i class="fa fa-hashtag me-2"></i>DASHMIN</h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="~/admin/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">Jhon Doe</h6>
                        <span>Admin</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="index.html" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-laptop me-2"></i>Elements</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a asp-controller="Service" asp-action="Index" class="dropdown-item">Services</a>
                        </div>
                    </div>
                    <a href="widget.html" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Widgets</a>
                    <a href="form.html" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Forms</a>
                    <a href="table.html" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Tables</a>
                    <a href="chart.html" class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>Charts</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="far fa-file-alt me-2"></i>Pages</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="signin.html" class="dropdown-item">Sign In</a>
                            <a href="signup.html" class="dropdown-item">Sign Up</a>
                            <a href="404.html" class="dropdown-item">404 Error</a>
                            <a href="blank.html" class="dropdown-item">Blank Page</a>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->


        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                <form class="d-none d-md-flex ms-4">
                    <input class="form-control border-0" type="search" placeholder="Search">
                </form>
                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-envelope me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex">Message</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="~/admin/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="~/admin/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="~/admin/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all message</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-bell me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex">Notificatin</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Profile updated</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">New user added</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Password changed</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all notifications</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img class="rounded-circle me-lg-2" src="~/admin/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                            <span class="d-none d-lg-inline-flex">John Doe</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">My Profile</a>
                            <a href="#" class="dropdown-item">Settings</a>
                            <a href="#" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->
        @RenderBody()
    <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-light rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href="#">Your Site Name</a>, All Right Reserved. 
                        </div>
                        <div class="col-12 col-sm-6 text-center text-sm-end">
                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            Designed By <a href="https://htmlcodex.com">HTML Codex</a>
                        </br>
                        Distributed By <a class="border-bottom" href="https://themewagon.com" target="_blank">ThemeWagon</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/admin/lib/chart/chart.min.js"></script>
    <script src="~/admin/lib/easing/easing.min.js"></script>
    <script src="~/admin/lib/waypoints/waypoints.min.js"></script>
    <script src="~/admin/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/admin/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/admin/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/admin/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/admin/js/main.js"></script>
</body>

</html>

LogicBack/Views/Shared/Components/Footer/Default.cshtml
@model HomeVM    
<footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-4">
        <div class="col-lg-5 col-md-12 footer-info">
          <a href="index.html" class="logo d-flex align-items-center">
            <span>@Model.Settings.FooterLogo</span>
          </a>
          <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
          <div class="social-links d-flex mt-4">
            @foreach (var item in Model.SocialMedias)
           {
               <a href="#" class="twitter"><i class="@item.Icon"></i></a>
           }
          </div>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">About us</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Terms of service</a></li>
            <li><a href="#">Privacy policy</a></li>
          </ul>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Our Services</h4>
          <ul>
            <li><a href="#">Web Design</a></li>
            <li><a href="#">Web Development</a></li>
            <li><a href="#">Product Management</a></li>
            <li><a href="#">Marketing</a></li>
            <li><a href="#">Graphic Design</a></li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
          <h4>Contact Us</h4>
          <p>
            A108 Adam Street <br>
            New York, NY 535022<br>
            United States <br><br>
            <strong>Phone:</strong> +1 5589 55488 55<br>
            <strong>Email:</strong> info@example.com<br>
          </p>

        </div>

      </div>
    </div>

    <div class="container mt-4">
      <div class="copyright">
        &copy; Copyright <strong><span>Logis</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/logis-bootstrap-logistics-website-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>

  </footer><!-- End Footer -->
  <!-- End Footer -->

LogicBack/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Logis Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="~/assets/img/favicon.png" rel="icon">
  <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
  <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
  <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="~/assets/css/main.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Logis - v1.0.1
  * Template URL: https://bootstrapmade.com/logis-bootstrap-logistics-website-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  @await Component.InvokeAsync("Header")
        @RenderBody()
        @await Component.InvokeAsync("Footer")

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/assets/vendor/purecounter/purecounter_vanilla.js"></script>
  <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="~/assets/vendor/aos/aos.js"></script>
  <script src="~/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="~/assets/js/main.js"></script>

</body>

</html>